# Generated by Django 4.1.1 on 2022-09-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0002_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="address",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="message",
            name="eth",
            field=models.FloatField(default="0"),
            preserve_default=False,
        ),
    ]
